### ISSUE TITLE
THANK YOU! How can I help?!

### ISSUE THREAD

**Issue by brotherdust** [AngainorDev/Maix-Amigo-Help#1]
Hi @AngainorDev ,
I got my Amigo's a couple of days ago and I'm having the same experience you've so kindly documented in this repo. I'd like to thank you for posting what information you have.

Are you open to pull requests? I'd like to help!

**Comment by AngainorDev** [comment]
Hi!

Thanks to you, and yes, I'm very open to pull requests.
I put that repo on hold for a while, waiting to see what will move on either on sipeed or community side ;)

Since, Sipeed added a more complete board definition config file, I'll need to check that out if supported by maixpy already.

Make yourself home and don't hesitate to PR or open issues for things you'd like to do but can't for now.

**Comment by brotherdust** [comment]
@AngainorDev I saw that they committed a board config for the Amigo a few days ago. I compiled a new firmware with those definitions, but touchscreen is not working. I have more debugging to do before I can figure out what's happening. Once I have something useful, I'll post a pull request. Thank you!
